name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: "0 12 * * 1"   # weekly Mon 12:00 UTC (optional)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff black pytest pytest-cov
      - name: Lint
        run: |
          ruff check .
          ruff format --check .
      - name: Tests
        run: |
          pytest -q
